version: "3.7"
networks:
  sensors:
    driver: bridge
services:
    app:
      build:
        args:
          user: john
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: sensors
      container_name: sensors-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - sensors

    db:
      image: mysql:5.7
      container_name: sensors-db
      restart: unless-stopped
      ports:
        - 3308:3306
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      networks:
        - sensors

    nginx:
      image: nginx:1.17-alpine
      container_name: sensors-nginx
      restart: unless-stopped
      ports:
        - 8001:80
      volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d
      networks:
        - sensors